const API = 'http://127.0.0.1:8000', $ = s => document.querySelector(s); let devices = [], token = sessionStorage.getItem('netradar_token'), socket;
const headers = () => token ? { Authorization: `Bearer ${token}` } : {};
async function request(path, options = {}) { const r = await fetch(API + path, { ...options, headers: { ...headers(), ...(options.headers || {}) } }); if (r.status === 401) { showLogin(); throw Error('Authentication required') } return r }
function statusClass(s) { return (s || 'UNKNOWN').toLowerCase() }
function render() { const counts = ['UP', 'DOWN', 'UNSTABLE', 'UNKNOWN'].map(s => [s, devices.filter(d => d.current_status === s).length]); $('#summary').innerHTML = counts.map(([s, n]) => `<div class="metric"><span class="status ${statusClass(s)}">${s}</span><b>${n}</b></div>`).join(''); $('#devices').innerHTML = devices.map(d => `<tr><td><b>${d.hostname}</b></td><td>${d.ip_address}</td><td>${d.device_type}</td><td>${d.vlan_id ?? '—'}</td><td>${d.criticality}</td><td><span class="status ${statusClass(d.current_status)}">${d.current_status}</span></td><td><button onclick="pollDevice('${d.id}')">Poll now</button></td></tr>`).join('') || '<tr><td colspan="7" class="muted">No devices have been added.</td></tr>'; $('#lastUpdate').textContent = `Updated ${new Date().toLocaleTimeString()}` }
async function load() { const r = await request('/api/devices'); devices = await r.json(); render() } async function pollDevice(id) { await request(`/api/devices/${id}/poll`, { method: 'POST' }) } window.pollDevice = pollDevice;
function addEvent(e) { const x = document.createElement('div'), d = e.device_info; x.className = `event ${statusClass(d.status)}`; x.innerHTML = `<b>${d.status}: ${d.hostname} (${d.ip_address})</b><br>${e.diagnostics.failure_reason || 'Reachable'} — ${e.diagnostics.details}`; $('#feed').prepend(x) }
function connect() { if (socket) socket.close(); const q = token ? `?token=${encodeURIComponent(token)}` : ''; socket = new WebSocket(API.replace('http', 'ws') + '/ws/live' + q); socket.onopen = () => { $('#connection').textContent = 'Live'; $('#connection').className = 'badge up'; socket.send('ready') }; socket.onmessage = e => { addEvent(JSON.parse(e.data)); load() }; socket.onclose = e => { if (e.code === 1008) { showLogin(); return } $('#connection').textContent = 'Reconnecting'; $('#connection').className = 'badge neutral'; setTimeout(connect, 2000) } }
function showLogin() { $('#loginOverlay').hidden = false; $('#connection').textContent = 'Sign in required'; $('#connection').className = 'badge neutral' } async function start() { try { await load(); $('#loginOverlay').hidden = true; connect() } catch (_) { } }
$('#loginForm').onsubmit = async e => { e.preventDefault(); const r = await fetch(API + '/api/auth/token', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(new FormData(e.target))) }); if (!r.ok) { $('#loginMessage').textContent = 'Sign-in failed.'; return } token = (await r.json()).access_token; sessionStorage.setItem('netradar_token', token); $('#loginMessage').textContent = ''; await start() }; $('#refresh').onclick = load; $('#deviceForm').onsubmit = async e => { e.preventDefault(); const fd = new FormData(e.target); const data = Object.fromEntries(fd); if (!data.vlan_id) delete data.vlan_id; else data.vlan_id = Number(data.vlan_id); if (!data.switch_port_ifindex) delete data.switch_port_ifindex; else data.switch_port_ifindex = Number(data.switch_port_ifindex); data.is_dns_server = fd.get('is_dns_server') === 'on'; const r = await request('/api/devices', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); $('#formMessage').textContent = r.ok ? 'Device added.' : 'Could not add device: ' + await r.text(); if (r.ok) { e.target.reset(); load() } }; start();